version: '3.8'

services:

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Backend

    ports:
      - 3306:3306
    volumes:
        - /tmp/data/:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3001:3001 #modificado para que corra en el puerto 3001
    environment:
      # MYSQL_ROOT_PASSWORD: 123456
      # MYSQL_DATABASE: faztdb
      - DATABASE_NAME=Backend
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=mysqldb
      